# Generated by Django 4.2.1 on 2023-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='Day',
            field=models.CharField(default=0, max_length=8),
            preserve_default=False,
        ),
    ]
