# Generated by Django 4.2.1 on 2023-05-19 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Movie',
        ),
        migrations.AddField(
            model_name='booking',
            name='movieName',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='seats',
            field=models.CharField(default=0, max_length=70),
            preserve_default=False,
        ),
    ]
